# =====================================================================
# Eureka Server - Servicio Público de Salud RedNorte
# Servidor de descubrimiento y registro de microservicios
# =====================================================================

spring.application.name=infraestructura-eureka
server.port=8761

# No se registra a sí mismo como cliente
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuración del servidor
eureka.server.renewal-percent-threshold=0.85
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.server.enable-self-preservation=true

spring.cloud.config.override-none=false
